service: rgc-ontology
frameworkVersion: '3'

# to deploy react front-end to s3
plugins:
  - serverless-finch

custom:
  client:
    bucketName: ${self:service}-ontologyui-${sls:stage}
    distributionFolder: client/build

provider:
  name: aws
  runtime: nodejs18.x
  environment:
    DYNAMODB_ONTOLOGY_MASTER_TABLE: ${self:service}-ontologyMasterTbl-${sls:stage}
    DYNAMODB_ONTOLOGY_HISTORY_TABLE: ${self:service}-ontologyHistoryTbl-${sls:stage}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:Get*"
        - "dynamodb:Query"
        - "dynamodb:Scan*"
        - "dynamodb:PutItem"
        - "dynamodb:UpdateItem"
        - "dynamodb:DeleteItem"
        - "dynamodb:BatchGetItem"
      Resource: 
        - arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${self:service}-ontologyMasterTbl-${sls:stage}
        - arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${self:service}-ontologyHistoryTbl-${sls:stage}
  httpApi:
    cors: true

functions:
  search:
    handler: search.handler
    events:
      - httpApi:
          path: /search
          method: get
  add:
    handler: add.handler
    events: 
      - httpApi:
          path: /add
          method: post          
  getById:
    handler: getById.handler
    events: 
      - httpApi:
          path: /getById
          method: get
  editById:
    handler: editById.handler
    events: 
      - httpApi:
          path: /editById
          method: put
  deleteById:
    handler: deleteById.handler
    events: 
      - httpApi:
          path: /deleteById
          method: delete

resources:
  Resources:
    OntologyMasterTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: conceptId
            AttributeType: N
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: conceptId
            KeyType: HASH
        TableName: ${self:service}-ontologyMasterTbl-${sls:stage}
    OntologyHistoryTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: conceptId
            AttributeType: N
          - AttributeName: timeStamp
            AttributeType: N
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: conceptId
            KeyType: HASH
          - AttributeName: timeStamp
            KeyType: RANGE
        TableName: ${self:service}-ontologyHistoryTbl-${sls:stage}

package:
  patterns:
    - '!client/**'